use_frameworks!

platform :ios, '18.0'

target 'Custom-Video-Player_Example' do
  pod 'CustomVideoPlayer', :path => '../'

  target 'Custom-Video-Player_Tests' do
    inherit! :search_paths

    
  end
end
